apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  strategy:
    type: Recreate  # Added strategy field
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: raghul1995/express-demo-app
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: gcr.io/google-samples/hello-app:2.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.88.114.134:8080   # Updated loadBalancerIP
  selector:
    app: hello
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zone-printer-deployment
spec:
  selector:
    matchLabels:
      app: zone-printer
  template:
    metadata:
      labels:
        app: zone-printer
    spec:
      containers:
      - name: zone-printer
        image: gcr.io/google-samples/zone-printer:0.2
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: zone-printer-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.88.114.134:4000   # Updated loadBalancerIP
  selector:
    app: zone-printer
  ports:
  - port: 4000
    targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami-deployment
spec:
  selector:
    matchLabels:
      app: whereami
  template:
    metadata:
      labels:
        app: whereami
    spec:
      containers:
      - name: whereami
        image: gcr.io/google-samples/whereami:v1.2.6
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: whereami-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.88.114.134:5000   # Updated loadBalancerIP
  selector:
    app: whereami
  ports:
  - port: 5000
    targetPort: 5000
