apiVersion: v1
kind: Service
metadata:
  name: {{ include "whereami-service.fullname" . }}
spec:
  type: LoadBalancer
  selector:
    app: whereami  # Update this line to match the deployment label for 'whereami'
  ports:
    - port: 5000
      targetPort: 5000
